import fs from 'fs/promises';
import { exec } from 'child_process';
import path from 'path';
import { promisify } from 'util';

const execAsync = promisify(exec);

// ==========================================
// TOT RETURN DETAILS
// ==========================================
const KRA_PIN = process.env.KRA_PIN || 'P000000000A';
const PERIOD_YEAR = '2026';
const PERIOD_MONTH = '01'; // e.g., '01' for January
const GROSS_SALES = '15000'; // Example sales amount

/**
 * Generates the XML payload for the TOT return.
 * NOTE: The structure below is a generic template. To match KRA absolutely 100%,
 * you can paste the exact XML contents of your manually validated .zip file here,
 * and replace the hardcoded values with these variables like ${KRA_PIN}.
 */
function generateKraTotXml(pin: string, year: string, month: string, sales: string): string {
    return `<?xml version="1.0" encoding="UTF-8"?>
<TurnoverTax>
    <TaxPayer>
        <PinNo>${pin}</PinNo>
    </TaxPayer>
    <ReturnPeriod>
        <Year>${year}</Year>
        <Month>${month}</Month>
    </ReturnPeriod>
    <SalesData>
        <GrossSales>${sales}</GrossSales>
    </SalesData>
</TurnoverTax>`.trim();
}

async function generateTotZip() {
    // 1. Prepare temp directory
    const outputDir = path.join(__dirname, '..', '..', 'tmp');
    await fs.mkdir(outputDir, { recursive: true });

    // Ensure filenames follow the format you usually see
    const xmlFilename = `${KRA_PIN}_TOT_Return.xml`;
    const xmlPath = path.join(outputDir, xmlFilename);
    const zipPath = path.join(outputDir, `${KRA_PIN}_TOT_${PERIOD_YEAR}${PERIOD_MONTH}.zip`);

    console.log(`Generating raw XML for PIN: ${KRA_PIN}...`);
    const xmlContent = generateKraTotXml(KRA_PIN, PERIOD_YEAR, PERIOD_MONTH, GROSS_SALES);
    await fs.writeFile(xmlPath, xmlContent, 'utf-8');

    console.log(`Zipping XML file into archive...`);
    // 2. We use PowerShell's built-in Compress-Archive since Node natively lacks a simple zip module without 3rd party deps
    try {
        await execAsync(`powershell.exe -NoProfile -Command "Compress-Archive -Path '${xmlPath}' -DestinationPath '${zipPath}' -Force"`);
    } catch (err) {
        console.error('Failed to create zip file (ensure you are running on Windows). Error:', err);
        return;
    }

    // 3. Clean up the raw XML file if desired (optional)
    await fs.rm(xmlPath, { force: true });

    console.log(`âœ… Successfully generated KRA TOT Return ZIP file!`);
    console.log(`Location: ${zipPath}`);
    console.log(`You can now compare this file to the one generated by the KRA Excel macro.`);
}

generateTotZip().catch(console.error);
