steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/taxpulse-498006/krafiler-repo/krafiler-api:latest', '-f', 'Dockerfile.compute', '.']
images:
  - 'us-central1-docker.pkg.dev/taxpulse-498006/krafiler-repo/krafiler-api:latest'
