import { Kysely, sql } from 'kysely';

export async function up(db: Kysely<any>): Promise<void> {
    await db.schema
        .createTable('clients')
        .ifNotExists()
        .addColumn('id', 'integer', (col) => col.primaryKey().autoIncrement())
        .addColumn('name', 'text', (col) => col.notNull())
        .addColumn('pin', 'text', (col) => col.notNull().unique())
        .addColumn('password', 'text', (col) => col.notNull())
        .addColumn('obligations', 'text', (col) => col.notNull())
        .addColumn('masterFileUrl', 'text')
        .addColumn('masterFileLabel', 'text')
        .addColumn('payrollSourceUrl', 'text')
        .addColumn('latestZipUrl', 'text')
        .addColumn('latestZipLabel', 'text')
        .addColumn('payeZipUrl', 'text')
        .addColumn('payeZipLabel', 'text')
        .addColumn('nssfFileUrl', 'text')
        .addColumn('nssfFileLabel', 'text')
        .addColumn('shaFileUrl', 'text')
        .addColumn('shaFileLabel', 'text')
        .addColumn('paye', 'text', (col) => col.defaultTo('na'))
        .addColumn('nssf', 'text', (col) => col.defaultTo('na'))
        .addColumn('sha', 'text', (col) => col.defaultTo('na'))
        .addColumn('eLevy', 'text', (col) => col.defaultTo('na'))
        .addColumn('vat', 'text', (col) => col.defaultTo('na'))
        .addColumn('tot', 'text', (col) => col.defaultTo('na'))
        .addColumn('mri', 'text', (col) => col.defaultTo('na'))
        .addColumn('dst', 'text', (col) => col.defaultTo('na'))
        .addColumn('payeAmount', 'real')
        .addColumn('nitaAmount', 'real')
        .addColumn('housingLevyAmount', 'real')
        .addColumn('nssfAmount', 'real')
        .addColumn('shaAmount', 'real')
        .addColumn('payeLastFiledDate', 'text')
        .addColumn('payeReceiptUrl', 'text')
        .addColumn('nssfLastFiledDate', 'text')
        .addColumn('nssfReceiptUrl', 'text')
        .addColumn('shaLastFiledDate', 'text')
        .addColumn('shaReceiptUrl', 'text')
        .addColumn('eLevyLastFiledDate', 'text')
        .addColumn('eLevyReceiptUrl', 'text')
        .addColumn('vatLastFiledDate', 'text')
        .addColumn('vatReceiptUrl', 'text')
        .addColumn('totLastFiledDate', 'text')
        .addColumn('totReceiptUrl', 'text')
        .addColumn('mriLastFiledDate', 'text')
        .addColumn('mriReceiptUrl', 'text')
        .addColumn('dstLastFiledDate', 'text')
        .addColumn('dstReceiptUrl', 'text')
        .addColumn('sector', 'text')
        .addColumn('email', 'text')
        .addColumn('phone', 'text')
        .addColumn('nssfLogin', 'text')
        .addColumn('nssfPassword', 'text')
        .addColumn('shaLogin', 'text')
        .addColumn('shaPassword', 'text')
        .addColumn('etimsLogin', 'text')
        .addColumn('etimsPassword', 'text')
        .addColumn('eLevyLogin', 'text')
        .addColumn('eLevyPassword', 'text')
        .execute();
}

export async function down(db: Kysely<any>): Promise<void> {
    await db.schema.dropTable('clients').execute();
}
