import fs from 'fs';
import path from 'path';
import { Router, Request, Response } from 'express';
import multer from 'multer';
import archiver from 'archiver';
import { generateComplianceFiles } from '../scripts/axon-extraction-engine';

const router = Router();

// Configure Multer for processing the uploaded CSV into memory or temp path.
// Using disk storage because the extraction engine streams from a path.
const uploadDir = path.join(__dirname, '../../uploads');
if (!fs.existsSync(uploadDir)) {
    fs.mkdirSync(uploadDir, { recursive: true });
}

const storage = multer.diskStorage({
    destination: (req, file, cb) => {
        cb(null, uploadDir);
    },
    filename: (req, file, cb) => {
        cb(null, `payroll_${Date.now()}.csv`);
    }
});

const upload = multer({ storage });

router.post('/generate-unified', upload.single('payrollFile'), async (req: Request, res: Response) => {
    try {
        if (!req.file) {
            return res.status(400).json({ error: 'No CSV file uploaded.' });
        }

        // Configuration values are parsed directly from the uploaded CSV in the updated pipeline.
        // We pass empty fallbacks here just as a typescript interface requirement.
        const config = {
            employerPin: 'P000000000A',
            nssfEmployerNo: 'N00000000',
            employerName: 'TEST COMPANY LTD',
            periodMMYYYY: '042026'
        };

        const options = {
            generatePaye: req.body.generatePaye !== 'false',
            generateNssf: req.body.generateNssf !== 'false',
            generateSha: req.body.generateSha !== 'false'
        };

        const inputCsvPath = req.file.path;
        console.log(`Processing file: ${inputCsvPath}`);

        // 1. Run the Extraction Engine
        const outputPaths = await generateComplianceFiles(inputCsvPath, config, options);

        // 2. We now have files generated by the engine. Zip them up for the user to download by piping to response.
        res.attachment(`Unified_Compliance_Package_${Date.now()}.zip`);
        
        const archive = archiver('zip', { zlib: { level: 9 } });
        
        archive.on('error', (err) => {
            console.error('Archiver error:', err);
            if (!res.headersSent) res.status(500).json({ error: 'Failed to compress compliance files.' });
        });

        archive.pipe(res);

        // Add the files to the final root package ZIP
        if (outputPaths.shaFilePath) archive.file(outputPaths.shaFilePath, { name: path.basename(outputPaths.shaFilePath) });
        if (outputPaths.nssfFilePath) archive.file(outputPaths.nssfFilePath, { name: path.basename(outputPaths.nssfFilePath) });
        if (outputPaths.payeZipPath) archive.file(outputPaths.payeZipPath, { name: path.basename(outputPaths.payeZipPath) });

        res.on('finish', () => {
            // Cleanup temp files after stream finishes
            console.log('Stream finished. Cleaning up files.');
            try {
                if (fs.existsSync(inputCsvPath)) fs.unlinkSync(inputCsvPath);
                if (outputPaths.shaFilePath && fs.existsSync(outputPaths.shaFilePath)) fs.unlinkSync(outputPaths.shaFilePath);
                if (outputPaths.nssfFilePath && fs.existsSync(outputPaths.nssfFilePath)) fs.unlinkSync(outputPaths.nssfFilePath);
                if (outputPaths.payeZipPath && fs.existsSync(outputPaths.payeZipPath)) fs.unlinkSync(outputPaths.payeZipPath);
            } catch(e) {}
        });

        await archive.finalize();
        console.log('Archive finalized successfully.');

    } catch (error: any) {
        console.error('Error generating payroll files:', error, error.stack);
        res.status(500).json({ error: error.message || 'Failed to generate unified payroll files.' });
    }
});

export default router;