import fs from 'fs';
import path from 'path';
import { Router, Request, Response } from 'express';
import multer from 'multer';
import archiver from 'archiver';
import { generateComplianceFiles } from '../scripts/axon-extraction-engine';

const router = Router();

// Configure Multer for processing the uploaded CSV into memory or temp path.
// Using disk storage because the extraction engine streams from a path.
const uploadDir = path.join(__dirname, '../../uploads');
if (!fs.existsSync(uploadDir)) {
    fs.mkdirSync(uploadDir, { recursive: true });
}

const storage = multer.diskStorage({
    destination: (req, file, cb) => {
        cb(null, uploadDir);
    },
    filename: (req, file, cb) => {
        cb(null, `payroll_${Date.now()}.csv`);
    }
});

const upload = multer({ storage });

router.post('/generate-unified', upload.single('payrollFile'), async (req: Request, res: Response) => {
    try {
        if (!req.file) {
            return res.status(400).json({ error: 'No CSV file uploaded.' });
        }

        // Configuration values are parsed directly from the uploaded CSV in the updated pipeline.
        // We pass empty fallbacks here just as a typescript interface requirement.
        const config = {
            employerPin: 'P000000000A',
            nssfEmployerNo: 'N00000000',
            employerName: 'TEST COMPANY LTD',
            periodMMYYYY: '042026'
        };

        const inputCsvPath = req.file.path;
        console.log(`Processing file: ${inputCsvPath}`);

        // 1. Run the Extraction Engine
        const outputPaths = await generateComplianceFiles(inputCsvPath, config);

        // 2. We now have 3 files generated by the engine. Zip them up for the user to download.
        const packageDir = path.join(__dirname, '../../output');
        if (!fs.existsSync(packageDir)) {
            fs.mkdirSync(packageDir, { recursive: true });
        }

        const packageFileName = `Unified_Compliance_Package_${Date.now()}.zip`;
        const packagePath = path.join(packageDir, packageFileName);

        const archive = archiver('zip', { zlib: { level: 9 } });
        const output = fs.createWriteStream(packagePath);

        archive.pipe(output);

        // Add the 3 files to the final root package ZIP
        archive.file(outputPaths.shaFilePath, { name: path.basename(outputPaths.shaFilePath) });
        archive.file(outputPaths.nssfFilePath, { name: path.basename(outputPaths.nssfFilePath) });
        archive.file(outputPaths.payeZipPath, { name: path.basename(outputPaths.payeZipPath) });

        await archive.finalize();

        // 3. Once zipping is completely done, stream it to the client
        output.on('close', () => {
            res.download(packagePath, packageFileName, (err) => {
                if (err) {
                    console.error('Download error:', err);
                }

                // Cleanup temp files
                fs.unlinkSync(inputCsvPath);
                fs.unlinkSync(outputPaths.shaFilePath);
                fs.unlinkSync(outputPaths.nssfFilePath);
                fs.unlinkSync(outputPaths.payeZipPath);
                fs.unlinkSync(packagePath);
            });
        });

    } catch (error) {
        console.error('Error generating payroll files:', error);
        res.status(500).json({ error: 'Failed to generate unified payroll files.' });
    }
});

export default router;