export enum KraErrorCode {
    UNKNOWN = 'UNKNOWN',
    SESSION_INVALID = 'SESSION_INVALID',
    CREDENTIALS_INVALID = 'CREDENTIALS_INVALID',
    CAPTCHA_INCORRECT = 'CAPTCHA_INCORRECT',
    ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
    PASSWORD_EXPIRED = 'PASSWORD_EXPIRED',
    MOBILE_VERIFICATION_REQUIRED = 'MOBILE_VERIFICATION_REQUIRED',
    ALREADY_FILED = 'ALREADY_FILED',
    PORTAL_UNAVAILABLE = 'PORTAL_UNAVAILABLE',
    RECEIPT_DOWNLOAD_FAILED = 'RECEIPT_DOWNLOAD_FAILED',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    NAVIGATION_ERROR = 'NAVIGATION_ERROR',
}
